using NavigationIntegrationSystem.Core.Enums;
using NavigationIntegrationSystem.Core.Logging;
using NavigationIntegrationSystem.Core.Models.DeviceCatalog;
using NavigationIntegrationSystem.Core.Models.Devices;
using NavigationIntegrationSystem.Core.Playback;
using NavigationIntegrationSystem.Devices.Implementations;
using NavigationIntegrationSystem.Devices.Runtime;

using System.Collections.Generic;

namespace NavigationIntegrationSystem.Devices.Modules;

// This module defines the Playback device, which streams data from a CSV file using the IPlaybackService.
public sealed class PlaybackDeviceModule : IInsDeviceModule
{
    #region Private Fields
    private readonly IPlaybackService m_PlaybackService;
    #endregion

    #region Properties
    public DeviceType Type => DeviceType.Playback;
    #endregion

    #region Constructors
    public PlaybackDeviceModule(IPlaybackService i_PlaybackService)
    {
        m_PlaybackService = i_PlaybackService;
    }
    #endregion

    #region Functions
    public DeviceDefinition BuildDefinition()
    {
        // These keys MUST match the CSV headers generated by the Recorder
        // See: IntegratedInsOutputItem.IntegratedInsOutputColumns
        return new DeviceDefinition(
            i_Type: DeviceType.Playback,
            i_Fields: new List<DeviceFieldDefinition>
            {
                // Time
                new("RcvTime[sec]", "Receive Time", "s"),
                new("OutputTime[sec]", "Output Time", "s"),

                // Position
                new("PositionLatValue", "Latitude", "deg"),
                new("PositionLonValue", "Longitude", "deg"),
                new("PositionAltValue", "Altitude", "m"),

                // Euler
                new("EulerRollValue", "Roll", "deg"),
                new("EulerPitchValue", "Pitch", "deg"),
                new("EulerAzimuthValue", "Azimuth", "deg"),

                // Rates
                new("EulerRollRateValue", "Roll Rate", "deg/s"),
                new("EulerPitchRateValue", "Pitch Rate", "deg/s"),
                new("EulerAzimuthRateValue", "Azimuth Rate", "deg/s"),

                // Velocity
                new("VelocityNorthValue", "Vel North", "m/s"),
                new("VelocityEastValue", "Vel East", "m/s"),
                new("VelocityDownValue", "Vel Down", "m/s"),
                new("VelocityTotalValue", "Vel Total", "m/s"),

                // Misc
                new("CourseValue", "Course", "deg"),
                new("StatusValue", "Status", "mask")
            });
    }

    public void Register(IInsDeviceRegistry i_Registry, ILogService i_LogService)
    {
        i_Registry.Register(Type, (def, cfg) => new PlaybackInsDevice(def, cfg, i_LogService, m_PlaybackService));
    }
    #endregion
}